version: 2
jobs: 
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          pip install django
          cd apps
          # migration
          python manage.py migrate
          # django test
          #python manage.py test
          