# Generated by Django 2.1.7 on 2019-04-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_item_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_name',
            new_name='image_url',
        ),
    ]
