# Generated by Django 2.1.7 on 2019-04-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20190404_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='average_purchase_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='next_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
